# Setup
title:        CamelWorks
tagline:      Physician Shift Scheduling Made Easy
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       CamelWorks
  url:        https://camel.works 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown